name: Check collaborators username within a PR

on:
  pull_request:
    paths: "terraform/**"

env:
  RUBY_VERSION: 3.1.0

jobs:
  check-collaborators-username:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - run: bundle install
      - name: Do check
        run: ruby bin/check-collaborators-usernames.rb
        env:
          OPS_BOT_TOKEN: ${{ secrets.OPS_BOT_TOKEN }}
          LOG_LEVEL: "info"
