name: Print PR changed terraform files

on:
  workflow_dispatch:

jobs:
  print-changed-pr-terraform-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print terraform files in PR
        run: git diff --no-commit-id --name-only -r origin/main | awk '{print $1}' | grep 'terraform/' | awk '{n=split($NF,a,"/");print $5,a[n]}' | sed 's/\.[^.]*$//'
