name: Targeted terraform plan
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths: 'terraform/**'

env:
  AWS_REGION:  "eu-west-2"
  S3_BUCKET_NAME: "cloud-platform-36623f774b9641d8697d65bdf6b030f5"
  TERRAFORM: terraform
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  TF_IN_AUTOMATION: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
      - run: scripts/targeted-plan.sh
